### if load balancer is configured on the kubernetes
---
kind: Service
apiVersion: v1
metadata:
  name: external-0
  namespace: kafka
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    targetPort: 9092
    port: 32001
    nodePort: 32001
  type: LoadBalancer
